# Generated by Django 3.2.8 on 2022-03-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='reference_cause_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='reference_cause_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
