# Generated by Django 3.2.8 on 2022-03-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220324_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentvoucher',
            old_name='reference_cause_id',
            new_name='ref_invoice_no',
        ),
        migrations.RenameField(
            model_name='receiptvoucher',
            old_name='reference_cause_id',
            new_name='ref_invoice_no',
        ),
    ]
