# Generated by Django 3.2.8 on 2022-06-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_monthlysubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='email',
            field=models.EmailField(default='some@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='first_name',
            field=models.CharField(default='joe', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='last_name',
            field=models.CharField(default='kane', max_length=255),
            preserve_default=False,
        ),
    ]
