# Generated by Django 3.2.8 on 2022-06-29 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donation', '0004_auto_20220628_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cause',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Causes'},
        ),
        migrations.AlterModelOptions(
            name='causecontent',
            options={'ordering': ['-id'], 'verbose_name_plural': 'CauseContents'},
        ),
        migrations.AddField(
            model_name='donation',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='donation.cause'),
        ),
        migrations.CreateModel(
            name='CauseContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='donation/CauseContentImage/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cause_content_images', to='donation.cause')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CauseContentImages',
                'ordering': ('-id',),
            },
        ),
    ]
