# Generated by Django 3.2.8 on 2022-03-21 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20220320_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmsmenu',
            options={'verbose_name_plural': 'CMSMenus'},
        ),
        migrations.AlterModelOptions(
            name='cmsmenucontent',
            options={'verbose_name_plural': 'CMSMenuContents'},
        ),
        migrations.RenameField(
            model_name='cmsmenucontent',
            old_name='menu',
            new_name='cms_menu',
        ),
    ]
