# Generated by Django 3.2.8 on 2022-03-23 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20220321_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsmenucontent',
            name='cms_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cms_menu_contents', to='cms.cmsmenu'),
        ),
    ]
