# Generated by Django 3.2.8 on 2022-06-21 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0005_alter_cmsmenucontent_cms_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmsmenu',
            options={'ordering': ('-id',), 'verbose_name_plural': 'CMSMenus'},
        ),
        migrations.AlterModelOptions(
            name='cmsmenucontent',
            options={'ordering': ('-id',), 'verbose_name_plural': 'CMSMenuContents'},
        ),
        migrations.CreateModel(
            name='CMSMenuContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='cms/ContentImage/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cms_menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cms_menu_content_images', to='cms.cmsmenu')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CMSMenuContentImages',
                'ordering': ('-id',),
            },
        ),
    ]
