# Generated by Django 3.2.8 on 2022-12-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_feegeneration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeeGeneration',
        ),
    ]
