# Generated by Django 3.2.8 on 2022-12-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('category', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('department_members', models.IntegerField()),
            ],
        ),
    ]
